syntax = "proto3";
import "google/protobuf/struct.proto";

package auth;

service AuthService {
  rpc Login (DefaultRequest) returns (DefaultResponse) {}
  rpc Logout (DefaultRequest) returns (DefaultResponse) {}
  rpc ValidateToken (ValidateTokenRequest) returns (ValidateTokenResponse) {}
}

message DefaultRequest {
  google.protobuf.Struct query = 1;
  google.protobuf.Struct params = 2;
  google.protobuf.Struct body = 3;
  google.protobuf.Struct headers = 4;
}

message DefaultResponse {
  int32 statusCode = 1;
  string message = 2;
  repeated string errors = 3;
  google.protobuf.Struct data = 4;
}

message ValidateTokenRequest {
  string token = 1;
}

message ValidateTokenResponse {
  bool isValid = 1;
  int32 userId = 2;
  string username = 3;
  repeated string roles = 4;
}